# Callbacks configuration for PyTorch Lightning training
# These callbacks are instantiated via Hydra's instantiate() function

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: "val_acc"  # name of the logged metric which determines when model is improving
  mode: "max"  # "max" means higher metric value is better, can be also "min"
  save_top_k: 1  # save only the best checkpoint (determined by val_acc)
  save_last: true  # additionally always save the last epoch checkpoint
  verbose: true  # enable verbose logging to see checkpoint saves
  dirpath: ${runtime.ckpt_dir}
  filename: "epoch_{epoch:03d}_val_acc_{val_acc:.4f}"
  auto_insert_metric_name: false
  every_n_epochs: 1  # check every epoch (but only save if it's best or last)
  save_on_train_epoch_end: false  # save after validation, not after training epoch

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val_acc"  # name of the logged metric which determines when model is improving
  mode: "max"  # "max" means higher metric value is better, can be also "min"
  patience: 10  # how many validation epochs of not improving until training stops
  min_delta: 0.0  # minimum change in the monitored metric needed to qualify as an improvement

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"

