# Callbacks configuration for PyTorch Lightning training
# These callbacks are instantiated via Hydra's instantiate() function

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: "val/loss"
  mode: "min"
  save_top_k: 1
  save_last: true
  verbose: true
  dirpath: ${runtime.ckpt_dir}
  filename: "epoch_{epoch:03d}_val_loss_{val/loss:.4f}"
  auto_insert_metric_name: false
  every_n_epochs: 1
  save_on_train_epoch_end: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/loss"
  mode: "min"
  patience: 10
  min_delta: 0.0

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"
