# Callbacks configuration for PyTorch Lightning training
# These callbacks are instantiated via Hydra's instantiate() function

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: "val_acc"  # name of the logged metric which determines when model is improving
  mode: "max"  # "max" means higher metric value is better, can be also "min"
  save_top_k: 1  # save k best models (determined by above metric)
  save_last: true  # additionally always save model from last epoch
  verbose: false
  dirpath: ${runtime.ckpt_dir}
  filename: "epoch_{epoch:03d}_val_acc_{val_acc:.4f}"
  auto_insert_metric_name: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val_acc"  # name of the logged metric which determines when model is improving
  mode: "max"  # "max" means higher metric value is better, can be also "min"
  patience: 10  # how many validation epochs of not improving until training stops
  min_delta: 0.0  # minimum change in the monitored metric needed to qualify as an improvement

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "epoch"

