# Architecture configuration for v1 (Prototypical Network baseline)

name: v1

# Model Architecture
model:
  encoder_type: conv4
  embedding_dim: ${features.embedding_dim}
  drop_rate: ${features.drop_rate}
  non_linearity: ${features.non_linearity}
  with_bias: ${features.with_bias}
  conv_channels: [64, 64, 64, 64]
  layer_4: ${features.layer_4}
  time_max_pool_dim: ${features.time_max_pool_dim}
  distance: euclidean
  n_mels: ${features.n_mels}

# Episode Configuration
episodes:
  n_way: ${train_param.k_way}
  k_shot: ${train_param.n_shot}
  n_query: 5
  episodes_per_epoch: ${train_param.num_episodes}
  val_episodes: 200
  test_episodes: 200
  seg_len: ${train_param.seg_len}
  adaptive_seg_len: ${train_param.adaptive_seg_len}

# Training Configuration
training:
  learning_rate: ${train_param.lr_rate}
  weight_decay: 1e-4
  max_epochs: 50
  optimizer: adamw
  scheduler: step
  scheduler_gamma: ${train_param.scheduler_gamma}
  scheduler_step_size: ${train_param.scheduler_step_size}
  gradient_clip_val: null
  negative_train_contrast: ${train_param.negative_train_contrast}
  load_weight_from: ${train_param.load_weight_from}
