# Architecture configuration for v2 (Enhanced Prototypical Network)
# Optimized for 8GB GPU (RTX 3070)
# Features: ResNet+Attention encoder, SpecAugment, Learnable distance metric

name: v2

# Model Architecture (Memory-efficient settings)
model:
  encoder_type: resnet_attention  # ResNet blocks with channel+temporal attention
  embedding_dim: 1024  # Memory-efficient (vs 2048)
  distance: learnable  # Options: euclidean, cosine, learnable
  in_channels: 1
  channels: [32, 64, 128, 256]  # Memory-efficient ResNet channels (vs [64,128,256,512])
  dropout: 0.1

# Data Augmentation (SpecAugment + Noise)
augmentation:
  use_augmentation: true
  use_spec_augment: true
  use_noise: true
  time_mask_pct: 0.15  # Mask up to 15% of time dimension
  freq_mask_pct: 0.15  # Mask up to 15% of frequency dimension

# Training Configuration
training:
  learning_rate: ${train_param.lr_rate}
  weight_decay: 1e-4
  max_epochs: 50
  scheduler: cosine  # Cosine annealing for better convergence
  scheduler_gamma: ${train_param.scheduler_gamma}
  scheduler_step_size: ${train_param.scheduler_step_size}
