# Architecture configuration for v3 (AST-based Prototypical Network)

name: v3

# Model Architecture
model:
  encoder_type: ast
  embedding_dim: 384
  distance: euclidean
  n_mels: ${features.n_mels}
  patch_freq: 8
  patch_time: 2
  max_time_bins: 32
  depth: 6
  num_heads: 6
  mlp_dim: 1536
  dropout: 0.1
  pooling: cls

# Episode Configuration
episodes:
  n_way: ${train_param.k_way}
  k_shot: ${train_param.n_shot}
  n_query: 5
  episodes_per_epoch: ${train_param.num_episodes}
  val_episodes: 200
  test_episodes: 200
  seg_len: ${train_param.seg_len}
  adaptive_seg_len: ${train_param.adaptive_seg_len}

# Training Configuration
training:
  learning_rate: ${train_param.lr_rate}
  weight_decay: 1e-4
  max_epochs: 100
  optimizer: adamw
  scheduler: cosine
  scheduler_gamma: ${train_param.scheduler_gamma}
  scheduler_step_size: ${train_param.scheduler_step_size}
  gradient_clip_val: 1.0
  negative_train_contrast: ${train_param.negative_train_contrast}
  load_weight_from: ${train_param.load_weight_from}
