# PyTorch Lightning Trainer configuration

_target_: lightning.Trainer

# Training duration
max_epochs: ${arch.training.max_epochs}

# Hardware
accelerator: "auto"
devices: "auto"
precision: "32"

# Reproducibility (use "warn" to allow ops without deterministic CUDA implementations)
deterministic: false

# Logging
log_every_n_steps: 10
enable_progress_bar: true

# Gradient clipping (optional, set to null to disable)
gradient_clip_val: null
gradient_clip_algorithm: "norm"

# Validation
check_val_every_n_epoch: 1
num_sanity_val_steps: 0

# Performance
enable_model_summary: true
